# 开发环境配置
listen_addr: "127.0.0.1:8080"
algorithm: "least_conn"  # 可选: round_robin, least_conn, weighted_rr, ip_hash

# 后端服务器配置
servers:
  - url: "http://localhost:8081"
    weight: 1
    health: "healthy"
    health_check_path: "/health"  # HTTP健康检查路径
  - url: "http://localhost:8082" 
    weight: 1
    health: "healthy"
    health_check_path: "/health"
  - url: "http://localhost:8083"
    weight: 1
    health: "healthy"
    health_check_path: "/health"

# 健康检查配置
health_check:
  interval: "10s"         # 检查间隔(10秒)
  timeout: "2s"           # 检查超时(2秒) 
  retry_count: 3          # 失败重试次数
  retry_interval: "1s"    # 重试间隔(1秒)
  default_path: "/health" # 默认检查路径
  max_failures: 3         # 最大失败次数

# 日志配置
log:
  level: "debug"          # 日志级别(debug/info/warn/error)
  format: "text"          # 日志格式(text/json)
  output: "stdout"        # 输出方式(stdout/file)
  file_path: ""           # 日志文件路径(当output=file时有效) 